### ISSUE TITLE
Can't iterate Collections in the STAC catalog with pystac_client

### ISSUE THREAD

**Issue by dmeaux-biotope** [eu-cdse/documentation#123]
Everything for the main catalog is returned as a STAC link, making the `Catalog.get_all_collections()` function return `None`. In addition, the links are all `'type' : 'application/json'`, which makes it impossible to iterate with any STAC objects. I'm having to parse and iterate through the JSON directly instead of being able to use `pystac_client`.

**Comment by Pratichhya** [comment]
@dmeaux-biotope, could you please create a ticket for it here https://helpcenter.dataspace.copernicus.eu/hc/en-gb/requests/new.  for this issue?

**Comment by dmeaux-biotope** [comment]
Done. Thanks for responding.

**Comment by fwfichtner** [comment]
@dmeaux-biotope I opened a similar ticket some weeks ago because of the invalid STAC API. According to their latest response they want to have this fixed within the next 3 weeks. Before that I also don't see how #101 can be resolved.

**Comment by floriandeboissieu** [comment]
@Pratichhya, any public link to the ticket ? And wouldn't it be wise to keep that issue open until it is solved ? 

Moreover, it would be nice to clearly mention in the [documentation](https://documentation.dataspace.copernicus.eu/APIs/STAC.html) that the current STAC API does not support pystac or pystac_client at moment, instead of [being vague on the issue](https://github.com/eu-cdse/documentation/commit/6df2712ab598af58cec0fc37335ea3441c57f5fa), it would certainly save some time for many of us...
