### ISSUE TITLE
title of "fragment" links hidden under header

### ISSUE THREAD

**Issue by soxofaan** [eu-cdse/documentation#179]
docs on openeo collections ( https://documentation-staging.dataspace.copernicus.eu/APIs/openEO/Python_Client/Python.html#collections)  :
> More information on how openEO “collections” relate to terminology used in other systems can be found in ([the openEO glossary](https://documentation-staging.dataspace.copernicus.eu/APIs/openEO/Glossary.html#eo-data-collections)).

when clicking the link https://documentation-staging.dataspace.copernicus.eu/APIs/openEO/Glossary.html#eo-data-collections  , the section title "EO data (Collections)" is hidden below large blue header

**Comment by Pratichhya** [comment]
With the proposed solution for the header in this PR  https://github.com/eu-cdse/documentation/pull/208 . The issue seems to be resolved

**Comment by soxofaan** [comment]
Is still an issue for me (using Firefox). I also don't see how #208 would resolve this problem

**Comment by Pratichhya** [comment]
> Is still an issue for me (using Firefox). I also don't see how #208 would resolve this problem

Ahh. Ok, yeah now I replicate it. It is happening only while using Firefox but seems okay with Edge/Chrome.

**Comment by Pratichhya** [comment]
Could the issue be due to Firefox's version? I retried it in Firefox, windows, and Ubuntu but couldn't replicate the issue. Nevertheless, the issue was observed in the Linux environment of Terrascope VM with Firefox version 102.8.0esr. The tested Ubuntu environment was 116.0.2 

Moreover, another issue encountered is that the staging link is not working. There for the time being, could you please test or use production link?

**Comment by Pratichhya** [comment]
The staging link is working again. Unaware of the exact cause, but was solved after a random change to check and push.

**Comment by soxofaan** [comment]
ok seems to work now at my side (e.g. https://documentation-staging.dataspace.copernicus.eu/APIs/openEO/Glossary.html#eo-data-collections in a fresh incognito window). 
Let's close this ticket
