### ISSUE TITLE
UDF source not shown for parcel delineation notebook on CDSE 

### ISSUE THREAD

**Issue by JeroenVerstraelen** [eu-cdse/documentation#462]
Source: https://jira.vito.be/browse/CDSE-85

The parcel delineation notebook at:
https://documentation.dataspace.copernicus.eu/APIs/openEO/openeo-community-examples/python/ParcelDelineation/Parcel%20delineation.html

Does not show the source of its UDFs:
```
FileNotFoundError: [Errno 2] No such file or directory: 'udf_segmentation.py'
```

**Comment by Pratichhya** [comment]
@VictorVerhaert @jdries, please correct and suggest to me if there are more solutions to this. Or which either of these could be a better one:

- add metadata in the notebook with a link to the main file location itself as shown in the image below
- edit the metadata in the submodule 
- instead of metadata give a hint in commnets(such as to create result folder/where to find the dependent files) in the notebook.

![image](https://github.com/eu-cdse/documentation/assets/39898768/3b1c41f6-f4da-4aef-80c6-f8edf7d6409d)

**Comment by jdries** [comment]
What about loading the UDF from github url directly?
________________________________

**Comment by VictorVerhaert** [comment]
The content of the udf's is one of the more important parts of this community example, so showing these on the page itself would be optimal I think. (perhaps make it clear that that code snippet is from a udf stored in a separate file)

**Comment by Pratichhya** [comment]
@VictorVerhaert agreed. But @jdries, I am sorry, not sure I understood it well, as at this moment, these notebooks are there in the placard through listing and as far as I know these listings do not give the option for sub-contents

**Comment by jdries** [comment]
I mean using:
https://open-eo.github.io/openeo-python-client/api.html#openeo.rest._datacube.UDF.from_url

like:
UDF.from_url("https://raw.githubusercontent.com/Open-EO/openeo-community-examples/main/python/ParcelDelineation/udf_segmentation.py")

ideally we could even check if the file exists locally, and otherwise load from url. That would make it work in all cases.

**Comment by Pratichhya** [comment]
I am sorry; maybe I confused you. The main concern is where to display the URL itself to suggest further to use it.

**Comment by Pratichhya** [comment]
FYI @KanerLev @Slegersj 

feedback on the description is received, on how to address notebooks that won't have description on their first cell. Such as:

![image](https://github.com/eu-cdse/documentation/assets/39898768/29245a24-4b80-459e-a468-89b314d8c56b)

**Comment by Pratichhya** [comment]
> FYI @KanerLev @Slegersj
> 
> feedback on the description is received, on how to address notebooks that won't have description on their first cell. Such as:

As a possible solution only image and title are displayed
